apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: praxe2026
type: Opaque
data:
  root-password: Um9vdFBhc3MxIQ==
  username: ZGVtbzEyYWRtaW4=
  password: RGVtbzEyUGFzczEh
  database: ZGVtbzEyZGI=
