apiVersion: v1
kind: Config
clusters:
  - name: bacprac2026
    cluster:
      server: https://178.18.244.197:6443
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkakNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTnpNME1USTBPREl3SGhjTk1qWXdNekV6TVRRek5EUXlXaGNOTXpZd016RXdNVFF6TkRReQpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTnpNME1USTBPREl3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFRMkJHZzM0ZWhBOUlNZWpSd0RZWVZhMlZ4aXRYc3lDOXdGN0t5Q3c3dDgKSkY0dFhqYkFvVXBETmFrNDZtOW5Rd1o1YkhnNmZwYi84RllBVHhKRUpNSWpvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVUtOeHp1MUIzQVEwTE1icDZ3Tmo5CmZYTzRIdTh3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnQmVPTFhiR3FTTm1RWGIwZk9SZDV2RG5HdzhSKzdOS04KeFErTjBNamRjK2dDSUZ3UUFqMHpIZUNiaHJGS0ZEWStmTldaMXptenFsem82WjduNUNibERjK3AKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
contexts:
  - name: praxe-user-1@bacprac2026
    context:
      cluster: bacprac2026
      namespace: praxe2026
      user: praxe-user-1
current-context: praxe-user-1@bacprac2026
users:
  - name: praxe-user-1
    user:
      token: eyJhbGciOiJSUzI1NiIsImtpZCI6InhvR2xmSnBLdXNvQWxoRmw4cmlvYXI5UGRza29hYy1ueDlINlFoYVlsQjQifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJwcmF4ZTIwMjYiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoicHJheGUtdXNlci0xLXRva2VuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InByYXhlLXVzZXItMSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImQyMGY0ZThmLTY0ZGUtNDM3NC1hZGZjLTllNjlhNmYwNzUwNiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpwcmF4ZTIwMjY6cHJheGUtdXNlci0xIn0.ZPsfVtba_ctsf1SNtqbcsvha6PkyvLVKFC2aAwSp2CnS7CmzJUdn8vV7T-_BQpTCAFyfdJsCk6dpjuK73MznElL69EGe1KwVUqh8wtRrxZbex5v4PbNCR1yiqF2Fbc_Uw_MpBFOkUyImQCyBzWyJGtpMWR8v38qUTTVSEcrDDfkxLDl_IicEmMojPnbT8g1fWUn7vJCvvLFEZvqOvbqPKtLLApJPuVva_wmATHtSIsolHdF6oMj28Jg7gaLE9SW1xrT0_8aoVpn-QtH7j3UMpbKBuFEeuxPj7xdnqatAbSGKMuOj_QK346vypCAm8sPNdSnO46SaW_iA_4CPVNxEww
