---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jakub-frontend
  namespace: praxe2026
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jakub-frontend
  template:
    metadata:
      labels:
        app: jakub-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/jakubkolinger/praxe-demo12-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4200
          resources:
            limits:
              cpu: "2000m"
              memory: "2048Mi"
            requests:
              cpu: "1000m"
              memory: "1024Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: jakub-frontend
  namespace: praxe2026
spec:
  selector:
    app: jakub-frontend
  ports:
    - port: 80
      targetPort: 4200
