name: Build and Push Frontend Docker Image

on:
  push:
    branches:
      - master
    paths:
      - 'src/main/frontend/**'         # spustí se pouze při změně souborů ve frontend/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Stáhni kód z repozitáře
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Přihlas se do GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # 3. Převeď jméno vlastníka na lowercase, získej SHA a zavolej skript
      - name: Set environment variables
        run: |
          OWNER_LOWER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')
          echo "OWNER_LOWER=$OWNER_LOWER" >> $GITHUB_ENV
          echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

          # Skriptu předáme vlastníka, token a název frontend balíčku
          VLASTNI_TAG=$(./get-tag.sh "$OWNER_LOWER" "${{ secrets.GHCR_TOKEN }}" "praxe-demo12-frontend")
          echo "VLASTNI_TAG=$VLASTNI_TAG" >> $GITHUB_ENV

      # 4. Sestav a nahraj image (Buď s vlastní verzí, nebo se SHA, a vždy s latest)
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./src/main/frontend
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LOWER }}/praxe-demo12-frontend:latest
            ${{ env.VLASTNI_TAG != '' && format('ghcr.io/{0}/praxe-demo12-frontend:{1}', env.OWNER_LOWER, env.VLASTNI_TAG) || format('ghcr.io/{0}/praxe-demo12-frontend:{1}', env.OWNER_LOWER, env.TAG) }}