name: Build and Push Frontend Docker Image

on:
  push:
    branches:
      - master
    paths:
      - 'src/main/frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set environment variables
        run: |
          OWNER_LOWER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')
          echo "OWNER_LOWER=$OWNER_LOWER" >> $GITHUB_ENV
          echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          
          # Skriptu předáme jen vlastníka, token a název frontend image
          VLASTNI_TAG=$(./get-tag.sh "$OWNER_LOWER" "${{ secrets.GHCR_TOKEN }}" "praxe-demo12-frontend")
          echo "VLASTNI_TAG=$VLASTNI_TAG" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./src/main/frontend
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LOWER }}/praxe-demo12-frontend:${{ env.TAG }}
            ghcr.io/${{ env.OWNER_LOWER }}/praxe-demo12-frontend:latest
            ${{ env.VLASTNI_TAG != '' && format('ghcr.io/{0}/praxe-demo12-frontend:{1}', env.OWNER_LOWER, env.VLASTNI_TAG) || '' }}